[package]
name = "actionkv"
version = "0.2.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
byteorder = "1.5.0"
crc = "3.2.1"
easy-repl = "0.2.1"
serde = { version = "1.0.213", features = ["derive"] }

[[bin]]
name = "akv"
path = "src/main.rs"
