[package]
name = "actionkv"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
crc = "3.2.1"
serde = { version = "1.0.213", features = ["derive"] }

[[bin]]
name = "akv_mem"
path = "src/main.rs"
